name: Run test with custom repository checkout 

on:
  workflow_call:
    inputs:
      repository:
        description: Path to the GitHub repository for which to run tests
        required: true
        type: string
      path:
        description: Local path on the runner for the custom repository checkout
        required: true
        type: string
      command:
        description: The command that the workflow should run
        default: vendor/bin/phpunit -c phpunit.xml.dist
        required: true
        type: string
    secrets:
      token:
        description: The token that will let the composer fetch private packages
        required: true


jobs:
  testing:
    runs-on: self-hosted

    services:
      mysql:
        image: mysql:8.0.26
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: cloudifi_test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        options: --health-cmd="mysqladmin ping" --health-interval=20s --health-timeout=5s --health-retries=6
      rabbitmq:
        image: thinhsan/mq-delayed-exchange
        ports:
          - 5672:5672
        env:
          RABBITMQ_DEFAULT_USER: testuser
          RABBITMQ_DEFAULT_PASS: testpass
        options: --health-cmd="rabbitmq-diagnostics -q ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        token: ${{ secrets.token }}

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Debug
      run: |
        pwd
        ls -la      

    - name: Install Dependencies
      run: composer install --no-scripts --prefer-dist
      env:
        COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.token }}"}}'
    
    - name: Clean working directory
      run: git clean -df && git checkout .

    - name: Run test suite
      run: ${{ inputs.command }}
      env:
        SYMFONY_DEPRECATIONS_HELPER: disabled
        RABBITMQ_URL: amqp://testuser:testpass@127.0.0.1:5672
        DATABASE_URL: mysql://testuser:testpass@127.0.0.1:3306/cloudifi_test
        DBSLAVE_HOST: 127.0.0.1
        DBSLAVE_PORT: 3306
        DBSLAVE_NAME: cloudifi_test
        DBSLAVE_USER: testuser
        DBSLAVE_PASS: testpass
        APP_ROOT: ${{ github.workspace }}/cloudi-fi/current/src/
        APP_SHARED: ${{ github.workspace }}/shared/
        APP_STORAGE: ../../../shared/
        JWT_SECRET: MxXJrWwRWxEidltCOsuWYDjqS8FUuCfz
